
editors_picks = [

"2Pac",
"3 Doors Down",
"50 Cent",
"A Fine Frenzy",
"A Tribe Called Quest",
"ABBA",
"Adele",
"Aerosmith",
"Air",
"Akon",
"Al Jarreau",
"Alanis Morissette",
"Alice Cooper",
"Alice in Chains",
"Alicia Keys",
"Alien Ant Farm",
"Alphaville",
"Amaral",
"America",
"Amon Tobin",
"Amy Winehouse",
"Aphex Twin",
"Arcade Fire",
"Arctic Monkeys",
"Aretha Franklin",
"Audioslave",
"Avenged Sevenfold",
"Avicii",
"Avril Lavigne",
"Backstreet Boys",
"Bad Religion",
"Band of Horses",
"Barbra Streisand",
"Barry Manilow",
"Basement Jaxx",
"Bat for Lashes",
"Beastie Boys",
"Beck",
"Bee Gees",
"Belle and Sebastian",
"Ben Harper",
"Beyoncé",
"Bill Evans",
"Bill Evans Trio",
"Bill Withers",
"Billie Holiday",
"Billy Idol",
"Billy Joel",
"Billy Talent",
"Björk",
"Black & White Knight",
"Black Eyed Peas",
"Black Flag",
"Black Sabbath",
"blink-182",
"Bloc Party",
"Blondie",
"Bloodhound Gang",
"Blue Öyster Cult",
"Blur",
"Bo Kaspers Orkester",
"Boards of Canada",
"Bob Dylan",
"Bob Marley & The Wailers",
"Bon Iver",
"Bon Jovi",
"Boney M.",
"Bonobo",
"Boston",
"Bright Eyes",
"Britney Spears",
"Bruce Springsteen",
"Bruce Springsteen & The E Street Band",
"Bruno Mars",
"Bryan Adams",
"Caesars",
"Cage the Elephant",
"Cake",
"Calvin Harris",
"Camera Obscura",
"Carly Simon",
"Cat Power",
"Cat Stevens",
"CeeLo Green",
"Céline Dion",
"Chairlift",
"Chicago",
"Chris Brown",
"Chris Rea",
"Christina Aguilera",
"Clarence Carter",
"Cocteau Twins",
"Coldplay",
"Counting Crows",
"Cream",
"Creedence Clearwater Revival",
"Cyndi Lauper",
"Daft Punk",
"Damien Rice",
"David Bowie",
"David Gray",
"David Guetta",
"deadmau5",
"Death Cab for Cutie",
"Deep Purple",
"Depeche Mode",
"Destiny's Child",
"Devendra Banhart",
"Diana Ross",
"Dido",
"Dire Straits",
"Disturbed",
"DJ Shadow",
"Don McLean",
"Dr. Dre",
"Dream Theater",
"Dropkick Murphys",
"Dune",
"Duran Duran",
"Earth, Wind & Fire",
"Eddie Vedder",
"Editors",
"Edward Sharpe & The Magnetic Zeros",
"Eels",
"El Canto del Loco",
"Electric Light Orchestra",
"Ella Fitzgerald",
"Ellie Goulding",
"Elliott Smith",
"Elton John",
"Elvis Costello",
"Elvis Presley",
"Emilíana Torrini",
"Eminem",
"Empire of the Sun",
"Enigma",
"Enya",
"Eric Clapton",
"Eros Ramazzotti",
"Estopa",
"Everything But the Girl",
"Faithless",
"Fall Out Boy",
"Fatboy Slim",
"Feist",
"Fergie",
"Fiona Apple",
"Fito Y Fitipaldis",
"Fleet Foxes",
"Fleetwood Mac",
"Flight of the Conchords",
"Flo Rida",
"Flogging Molly",
"Florence + the Machine",
"Fluke",
"Foo Fighters",
"Foster the People",
"Four Tet",
"Frank Sinatra",
"Franz Ferdinand",
"Frou Frou",
"Gang Starr",
"Gary Moore",
"Gary Numan",
"Gavin DeGraw",
"Genesis",
"George Michael",
"Gnarls Barkley",
"Goldfrapp",
"Good Knight Productions",
"Gorillaz",
"Grateful Dead",
"Green Day",
"Groove Armada",
"Guns N' Roses",
"Gwen Stefani",
"Håkan Hellström",
"Hall & Oates",
"Heart",
"Herbie Hancock",
"Him",
"Hoobastank",
"Hooverphonic",
"Hot Chip",
"Ice Cube",
"Iggy Pop",
"Imogen Heap",
"In Flames",
"Incubus",
"Infected Mushroom",
"Ingrid Michaelson",
"Interpol",
"Iron & Wine",
"Iron Maiden",
"J.J. Cale",
"Jack Johnson",
"Jackson Browne",
"James Blunt",
"James Brown",
"Jamie Cullum",
"Jamie T",
"Jamiroquai",
"Janis Joplin",
"Jason Derülo",
"Jason Mraz",
"Jay-Z",
"Jennifer Lopez",
"Jessie J",
"Jet",
"Jethro Tull",
"Jimmy Eat World",
"Joaquín Sabina",
"Joe Cocker",
"Joe Jackson",
"John Coltrane",
"John Legend",
"John Lennon",
"John Mayall & The Bluesbreakers",
"John Mayer",
"John Mellencamp",
"Johnny Cash",
"Joni Mitchell",
"José González",
"Journey",
"Judas Priest",
"Julio Iglesias",
"Justice",
"Justin Bieber",
"Justin Timberlake",
"Kaiser Chiefs",
"Kansas",
"Kanye West",
"Kasabian",
"Kate Nash",
"Katy Perry",
"Ke$ha",
"Kelly Clarkson",
"Kent",
"Kings of Convenience",
"Kings of Leon",
"Kiss",
"Klaxons",
"Kylie Minogue",
"Lady Gaga",
"Lamb",
"Lars Winnerbäck",
"Laurent Garnier",
"Lauryn Hill",
"LCD Soundsystem",
"Leftfield",
"Lemon Jelly",
"Lenka",
"Lenny Kravitz",
"Leonard Cohen",
"Lil' Wayne",
"Lily Allen",
"Limp Bizkit",
"Linkin Park",
"Lionel Richie",
"LMFAO",
"Lou Reed",
"Lykke Li",
"Lynyrd Skynyrd",
"M.I.A.",
"M83",
"Madonna",
"Manic Street Preachers",
"Mariah Carey",
"Marilyn Manson",
"Mark Knopfler",
"Maroon 5",
"Marvin Gaye",
"Mary J. Blige",
"Massive Attack",
"Maxïmo Park",
"Meat Loaf",
"Megadeth",
"Melody Gardot",
"Men at Work",
"Metric",
"MGMT",
"Michael Bublé",
"Michael Jackson",
"Miike Snow",
"Miles Davis",
"Miley Cyrus",
"Millencolin",
"Misfits",
"Moby",
"Modest Mouse",
"Moloko",
"Morcheeba",
"Motörhead",
"Muse",
"My Chemical Romance",
"N.W.A",
"Nas",
"Nat King Cole",
"Neil Diamond",
"Neil Young",
"Nelly Furtado",
"New Order",
"Nick Cave & The Bad Seeds",
"Nickelback",
"Nicki Minaj",
"Nightmares on Wax",
"Nightwish",
"Nina Simone",
"Nine Inch Nails",
"Nirvana",
"No Doubt",
"NOFX",
"Norah Jones",
"Oasis",
"OK Go",
"OneRepublic",
"Orbital",
"Orchestral Manoeuvres in the Dark",
"Otis Redding",
"OutKast",
"Owl City",
"Ozzy Osbourne",
"P!nk",
"Paolo Nutini",
"Papa Roach",
"Paramore",
"Passion Pit",
"Patti Smith",
"Paul McCartney",
"Paul Weller",
"Pearl Jam",
"Pet Shop Boys",
"Peter Bjorn and John",
"Phil Collins",
"Phoenix",
"Pitbull",
"Pixies",
"PJ Harvey",
"Placebo",
"Portishead",
"Primal Scream",
"Prince",
"Prodigy",
"Public Enemy",
"Pulp",
"Queen",
"Queens of the Stone Age",
"R. Kelly",
"R.E.M.",
"Radiohead",
"Rage Against the Machine",
"Ramones",
"Rancid",
"Ratatat",
"Ray Charles",
"Ray LaMontagne",
"Razorlight",
"Red Hot Chili Peppers",
"Regina Spektor",
"REO Speedwagon",
"Rihanna",
"Rilo Kiley",
"Rise Against",
"Robbie Williams",
"Robyn",
"Rod Stewart",
"Roxy Music",
"Röyksopp",
"Run-D.M.C.",
"Rush",
"Ryan Adams",
"Sade",
"Sam & Dave",
"Santana",
"Scooter",
"Sean Paul",
"Shakira",
"She & Him",
"Sia",
"Sigur Rós",
"Simon & Garfunkel",
"Simple Minds",
"Simply Red",
"Skillet",
"Skrillex",
"Snoop Dogg",
"Snow Patrol",
"Sonic Youth",
"Soundgarden",
"Spice Girls",
"Steely Dan",
"Stevie Wonder",
"Sting",
"Sublime",
"Sufjan Stevens",
"Sum 41",
"Superchic[k]",
"Supertramp",
"Swedish House Mafia",
"System of a Down",
"T.I.",
"Taio Cruz",
"Talking Heads",
"Tears for Fears",
"Tegan and Sara",
"Tenacious D",
"The Animals",
"The Asteroids Galaxy Tour",
"The Band",
"The Beach Boys",
"The Beatles",
"The Bird and the Bee",
"The Black Keys",
"The Cardigans",
"The Cars",
"The Chemical Brothers",
"The Clash",
"The Coral",
"The Cranberries",
"The Cure",
"The Doobie Brothers",
"The Doors",
"The Flaming Lips",
"The Fratellis",
"The Future Sound of London",
"The Game",
"The Hellacopters",
"The Hives",
"The Human League",
"The Isley Brothers",
"The Jackson 5",
"The Jimi Hendrix Experience",
"The Killers",
"The Kinks",
"The Kooks",
"The Last Shadow Puppets",
"The Libertines",
"The Lonely Island",
"The Magnetic Fields",
"The National",
"The Nitty Gritty Dirt Band",
"The Notorious B.I.G.",
"The Offspring",
"The Orb",
"The Police",
"The Postal Service",
"The Prodigy",
"The Raconteurs",
"The Rolling Stones",
"The Script",
"The Shins",
"The Smashing Pumpkins",
"The Smiths",
"The Sounds",
"The Stranglers",
"The Strokes",
"The Supremes",
"The Ting Tings",
"The Vaccines",
"The Verve",
"The Vines",
"The White Stripes",
"The Who",
"The Wombats",
"The xx",
"Thievery Corporation",
"Thin Lizzy",
"Tiësto",
"Timbaland",
"Tina Turner",
"Tom Petty and The Heartbreakers",
"Tom Waits",
"Toto",
"Train",
"Tricky",
"Turbonegro",
"Two Door Cinema Club",
"Tycho",
"U2",
"UB40",
"Underworld",
"Usher",
"Vampire Weekend",
"Van Halen",
"Van Morrison",
"Veronica Maggio",
"We Are Scientists",
"Weezer",
"Westlife",
"Whitney Houston",
"Within Temptation",
"Wolfgang Amadeus Mozart",
"Wolfmother",
"Xzibit",
"Yeah Yeah Yeahs",
"Yello",
"Yes",
"Zero 7",
"ZZ Top",
"植松伸夫",

]
